### ISSUE TITLE
No way to contact

### ISSUE THREAD

**Issue by jprice4444** [MorpheusAIs/Docs#17]
Hello, I accidentally sent stETH to the multisig on launch and have no way to contact the people on the multisig. the wording in this tweet confused me and assumed that on launch I could send there to stake https://x.com/MorpheusAIs/status/1754949646336553131?s=20
If there is anyway to contact the multisig plz lmk as I would appreciate getting it sent back. 
here is the txn https://etherscan.io/tx/0x7bb90aa13d5189467880a280b8806bcd54879e891f8e1060d024b76f7a88dda7
Sorry to raise as an issue on github, but dont know where else to find a contact for people on the multisig.

**Comment by jprice4444** [comment]
Any1 know how to get in contact with someone on multisig? Havent been able to find a discord or anything, tweets got ignored. they mentioned something about refunding people who sent to contract, but initial tweet was confusing.

**Comment by antonbosss** [comment]
Please join Discord and send your inquire to tech support channel
https://discord.gg/WUMewhpD

**Comment by betterbrand** [comment]
@jprice4444 
considering this handled.  Please note otherwise.
