### ISSUE TITLE
Restructuring docs to improve readability

### ISSUE THREAD

**Issue by tster** [MorpheusAIs/Docs#42]
The current docs structure seems suboptimal -- there is no clear starting point and it's hard to navigate, with information for various stakeholders (and languages!) mixed together.

Would like to propose a new, hierarchical structure where international docs are kept separate. For instance:

- readme.md
- Overview/Concepts
- User Guides
- Morpheus Node
- Contributing
- Architecture/Smart Contracts
- International
  - French
  - Chinese
  - Hindi
  - etc
- Archive

Pending feedback from contributors I'll begin working on a PR that implements this or another clearer structure.

**Comment by antonbosss** [comment]
Hi Thomas. Thank you for your initiative. 
Just to let you know, that repository reorganisation is ongoing. It started last week with moving all the documentation from MorpheusAI repo here and I have  translations reorg planned for the next week.
Any other changes like renaming/moving main docs will likely result in dozens of broken links among Morpheus repositories, websites, socials, announcements, etc.
